### ISSUE TITLE
[Bug - Edge Browser] chrome.storage.managed API broken in Edge 128+

### ISSUE THREAD

**Issue by 6112** [microsoft/MicrosoftEdge-Extensions#179] opened 2024-08-12 16:42 UTC
**Describe the bug**
The `chrome.storage.managed` API (to get policies) is currently broken in Edge Beta/Dev/Canary. This breaks my extension ([Legacy Browser Support](https://microsoftedge.microsoft.com/addons/detail/legacy-browser-support-fo/acallcpknnnjahhhapgkajgnkfencieh)), and breaks all extensions using enterprise policies.

**To Reproduce**
1. Install any MV3 extension that uses a ServiceWorker and has the `storage` permission. I used [Cornify](https://chromewebstore.google.com/detail/cornify-unicorn-and-rainb/ghdnfbmfflgelndafnlgabneckbmfpla) in my testing.
2. In edge://extensions, open DevTools for the extension's `ServiceWorker`
3. Run this snippet in the console:

```js
chrome.storage.managed.get('this_string_does_not_matter').then(() => console.log('policies work fine'));
```

**Expected behavior**
The snippet prints "policies work fine" in the console.

**Actual behavior**
The snippet prints nothing to the console, because `chrome.storage.managed.get()` never completes.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge Beta
 - Version: 128.0.2739.9

**Additional context**
Edge 127 and below work fine. I couldn't repro this issue in Chromium, so it looks like a downstream regression. Assuming Edge uses the same release schedule as Chromium, Edge 128 reaches Stable next week.

Please help me route this bug to the Edge team for prioritization

**Comment by mukul-p** [comment] 2024-08-13 10:48
I tried n followed the repro steps in three variants for Edge. But I was not able to repro with the three variants of Edge

Stable : Version 127.0.2651.86 (Official build) (64-bit)
Beta : Version 128.0.2739.22 (Official build) beta (64-bit) [Nicolas, can you check on this version of Beta?]
Canary : Version 129.0.2772.0 (Official build) canary (64-bit)

I am running Microsoft Windows [Version 10.0.22631.3880]

Thanks for reaching out. I am part of Edge Extensions team.

**Comment by mukul-p** [comment] 2024-08-14 13:50
I was able to repro this issue.
Thanks to Nicolas for providing a consistent repro.
_things work fine the first time with a fresh profile. But after restarting Edge, I started getting the bug._

**Comment by 6112** [comment] 2024-08-14 15:17
@mukul-p How optimistic are you about fixing this before 128 reaches Stable? IIUC that's in <1 week, so it's a very tight timeline.

I ask because my extension does `await chrome.storage.managed.get(...)` during startup. If it never resolves, the entire extension is broken. In retrospect, maybe that wasn't the best design decision.

I can always hotfix it with a workaround (by breaking policies), but IME Edge Add-ons reviews take close to a week. I suppose it would be prudent for me to submit my hotfix for review today...

**Comment by 8971-certainc** [comment] 2024-08-19 01:49
Will be fixed in the 128 release taking place this week?

**Comment by demirten** [comment] 2024-10-18 12:38
It is still not working on the latest 130.0.2849.46 build.

**Comment by apurvabhansali** [comment] 2024-10-18 16:21
we also never had any issues before 130.0.2849.46.  Today, multiple customers using our extension are reporting it is not working.  When we debug it is the same issue.  When we do chrome.storage.managed.get we get an exception "Error: Extension Context Invalidated. at chrome-extension:// <extension file with line number>"

**Comment by mkruger-msft** [comment] 2024-10-18 16:58
> we also never had any issues before 130.0.2849.46. Today, multiple customers using our extension are reporting it is not working. When we debug it is the same issue. When we do chrome.storage.managed.get we get an exception "Error: Extension Context Invalidated. at chrome-extension:// "

@demirten and @apurvabhansali, 
Is this on the stable channel or the beta channel of 130.0.2849.46? 

The original issue has only been a beta channel problem as the code related to this is disabled for stable. This code disablement has not changed for the v130 stable release. If this is occurring on stable, this may be a separate issue.

The fix for this issue is tracking to the v131 beta. It is currently in the Dev channel 131.0.2889.0 if you'd like to test there.

**Comment by apurvabhansali** [comment] 2024-10-18 17:03
Hi, this is happening in customer production environments where the browser just got updated to 130.0.2849.46.  I performed the same update on my own laptop and am seeing the same issue.

If I remove my profile and sign-in using my profile again, then it works, but if I close the browser and reopen it, the api again fails.

Doing some more debugging and will update.

**Comment by mkruger-msft** [comment] 2024-10-18 17:26
@6112 is it possible for you to test out your extension with the Edge current dev channel for v131 that is available now, or a Edge v131 beta that will be available next week around Thursday? I'd like to be sure the change corrects your original issue and does not regress other areas for you.

**Comment by apurvabhansali** [comment] 2024-10-18 17:44
Ok, some more steps.  When I bring up the browser I am currently in this situation with profiles (this is when I click the profile icon in the top left corner)

![Image](https://github.com/user-attachments/assets/816a3a36-5013-4986-b011-4d2db3322b1b)

Now, if I select my "Work" profile (this profile has our extension loaded) and click on our extension icon at the top, we call chrome.managed.storage.get.  This is failing at this point.

Now, I can go to ... -> settings -> profile and I see the following

![Image](https://github.com/user-attachments/assets/f237ebf7-fd39-404c-b107-7183e744ef50)

If I delete profile 1 at the bottom and then close the browser, then the icon in my taskbar changes to:

![Image](https://github.com/user-attachments/assets/f51b4b1c-0dd3-469d-be14-d03487fef480)

If I click the incorrect icon, the Edge browser starts again and if I click the profile icon in the top left corner, I again see the first screen shot I have posted above.  Once again I select my work profile and now clicking the extension causes chrome.managed.storage.get call to work properly.  I once again close the browser, and now the icon is restored to what is seen below. 

![Image](https://github.com/user-attachments/assets/96f8d46f-9ef2-43ac-b2a2-18e98070c0b3)

When I click the icon, again I start like the first screenshot showing profile 1 at the top.  If I again select my work profile (2nd time after delete profile 1), I am back in the same situation where clicking our icon causes our extension to call chrome.managed.storage.get and the call fails.  

I can rinse and repeat by deleting profile 1, then it will work the first time I select my work profile and after the 2nd time it will not work.  

Hope this helps.  Again, all done in production browser.  Let me see if I can test with the 131 channel.

Apurva

**Comment by apurvabhansali** [comment] 2024-10-18 18:11
same problem in v131 dev channel browser.  Only difference is that I don't see this phantom profile 1 and when I click the icon in the top right corner.  Basically, the browser always starts with my work profile, and the extension is not working by failing the chrome.managed.storage.get call.  I remove my profile by going to "...->settings->profiles" and clicking the trash can icon next to my profile.  if I close and restart the browser, I am prompted to sign in again and I select my account.  It now again logs me into my work profile and the extensions works the first time.  If I close the browser and re-open it defaults to my work profile, but extension is not working again.

Again, I can rinse and repeat, if I delete the profile and start over, it works the first time, but no time after that.

**Comment by apurvabhansali** [comment] 2024-10-18 18:14
And just to re-iterate, this was all working fine before our customers (and myself) upgraded to v130 on stable production browser.  Also, no issue on Chrome after V130 upgrade.

**Comment by 6112** [comment] 2024-10-18 18:49
> @6112 is it possible for you to test out your extension with the Edge current dev channel for v131 that is available now

My extension is broken on Beta (130.0.2849.46), and working on Dev (131.0.2889.0).

I haven't tested with a fresh profile like @apurvabhansali, though

**Comment by apurvabhansali** [comment] 2024-10-19 04:29
I have a 3rd customer with 100+ employees that are all affected by this 130.0.2859.46 release breaking our extension.  We use the managed storage api so that enterprise customers can push the settings for our extension via group policy.  I would suspect many extensions do this and are currently broken.  

Any feedback on why this has broken?  I think this will heat up with our customers next week.

**Comment by andreyta2020** [comment] 2024-10-21 12:21
Our extension is also stopped working because the managed storage api (which worked in Edge 129) is not working in Edge 130.0.2849.46

**Comment by StasSeraphic** [comment] 2024-10-21 12:27
Same here from 130, we need a solution ASAP!

**Comment by takakobem** [comment] 2024-10-21 12:46
Same here from 130. This issue is extremely critical for us. We request an urgent fix.

**Comment by apurvabhansali** [comment] 2024-10-21 15:00
@mkruger-msft @ManikanthMSFT is it possible to get a status update on this issue?  Has your team been able to recreate the issue and any ETA on a fix?  As you can see it is affecting multiple folks and is critical because I'm sure like our extension, most extensions are using this API to read enterprise wide settings for their extension that are pushed out via GPO, so it will render the extension DOA until it is resolved.

**Comment by ManikanthMSFT** [comment] 2024-10-21 15:03
Hey @apurvabhansali, we are currently looking into the issue and will update you as soon as we have more information.

We appreciate your patience in the meantime.

**Comment by colingm** [comment] 2024-10-21 15:08
@ManikanthMSFT we have recently found the same issue. It looks like in our case 129 was working fine, 130 was broken again, and then the current dev 131 seems to be fine again.

**Comment by chickahoona** [comment] 2024-10-21 15:54
So a known defect from August was now released in production with v130 ... Multiple enterprise customers are complaining now and all I can do is tell them to use Chrome...

**Comment by apurvabhansali** [comment] 2024-10-21 17:10
> [@ManikanthMSFT](https://github.com/ManikanthMSFT) we have recently found the same issue. It looks like in our case 129 was working fine, 130 was broken again, and then the current dev 131 seems to be fine again.

So for us v131 is not working either.  I don't know if @takakobem @StasSeraphic and @andreyta2020 can try on 131 also.

**Comment by takakobem** [comment] 2024-10-21 17:22
@apurvabhansali with 130 it seemed to work properly on the first launch, but it stopped working from the second time onwards.

**Comment by StasSeraphic** [comment] 2024-10-21 17:25
> > [@ManikanthMSFT](https://github.com/ManikanthMSFT) we have recently found the same issue. It looks like in our case 129 was working fine, 130 was broken again, and then the current dev 131 seems to be fine again.
> 
> So for us v131 is not working either. I don't know if [@takakobem](https://github.com/takakobem) [@StasSeraphic](https://github.com/StasSeraphic) and [@andreyta2020](https://github.com/andreyta2020) can try on 131 also.

131 seems to work for us

**Comment by ihiroky** [comment] 2024-10-21 17:25
Same here on 130 but works on 129 , and I'm in similar situation to @apurvabhansali on 131 in dev channel  (my extension works for the first time on 131, but it isn't working after restarting edge)

Even on 130, it works for the first time if I reinstall edge, but it stops working again after retarting edge

**Comment by apurvabhansali** [comment] 2024-10-21 17:28
My observation is that it is not just after fresh install.  If you delete your profile and restart edge, then it will work fine the first time, but then after that it does not work.  It has something to do with user profile.

**Comment by montrosb** [comment] 2024-10-22 13:31
This issue is also negatively affecting AdBlock  in the 130.0.2849.46 version of MS Edge on Windows 11.  We've had a large number of users report various issues with Adblock on MS Edge.


An update from Microsoft regarding this issue would be very helpful.

**Comment by ManikanthMSFT** [comment] 2024-10-22 13:39
Hey @apurvabhansali, @montrosb, thank you for your patience as we work through this issue. Our team has reviewed the initial comments and is currently investigating further. We believe there may be an additional issue contributing to the symptoms you’re experiencing, which requires more time to thoroughly investigate and identify the changes.

We understand the inconvenience this may cause and appreciate your understanding as we work towards a resolution. We will keep you updated on our progress and notify you as soon as we have more information.

Thank you for your continued patience and support.

**Comment by stephanie-jean** [comment] 2024-10-22 14:47
Hey @ManikanthMSFT ,
Thank you for addressing this issue. We’ve encountered significant challenges with this bug affecting most of our edge customers since our extension need to access managed storage.
When can we expect a solution? Do we know if there is any type of workaround that can be preformed until solving this issue?

**Comment by karlbecker** [comment] 2024-10-22 19:56
Noting that due to the large number of write-ins from our customers, we would really appreciate an estimated date that the fix will arrive.  

Since this was not broken until 130.0.2849.46, I am really hoping and optimistic that it won't be more than a couple days.  

This is seriously impacting a massive number of users as we can see here.  If there is any other place @ManikanthMSFT for us to escalate this issue, please let us know, because this is absolutely detrimental to millions of users of browser extensions.

**Comment by ihiroky** [comment] 2024-10-23 00:46
Edge 130.0.2849.52 is released, but the situation remains the same 😢

**Comment by apurvabhansali** [comment] 2024-10-23 02:25
and like last time, when the browser updated, then first time it worked, but after closing and opening browser again, it stopped working.

**Comment by mkruger-msft** [comment] 2024-10-23 03:26
Thank you for the reports and additional information. It is appreciated. We continue to investigate this issue and are treating it as a critical priority.

**Comment by apurvabhansali** [comment] 2024-10-23 03:28
> Thank you for the reports and additional information. It is appreciated. We continue to investigate this issue and are treating it as a critical priority.

Thanks!  Please keep giving us daily updates if possible because our customers are asking us for the same.

**Comment by mkruger-msft** [comment] 2024-10-23 17:00
I believe we have pinned down the change that caused this to break and are getting this reverted in the stable and beta channels for the next release. The exact schedule time of the release depends on a number of things, but it is scheduled for this week.

**Comment by sandeepchads** [comment] 2024-10-23 17:20
This issue is impacting multiple extensions for consumers and enterprises. As @mkruger-msft mentioned, we have the root cause and we are fixing this at a priority. Thank you all for bringing this to our notice. 🙏

**Comment by sandeepchads** [comment] 2024-10-24 04:30
You can track updates on this issue here: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-known-issues#high-impact-issues

**Comment by karlbecker** [comment] 2024-10-24 12:44
@sandeepchads  just a note that when I visit that webpage right now, it says

> This site can’t provide a secure connection
> learn.microsoft.com sent an invalid response.
> ERR_SSL_PROTOCOL_ERROR

Hopefully that can be fixed soon so we can track issue updates.

**Comment by mkruger-msft** [comment] 2024-10-24 21:49
Microsoft Edge stable v130.0.2849.56 is rolling out now and contains the fix for this issue.

**Comment by Droxi-Raveh** [comment] 2024-10-28 19:59
Hi, we're still experiencing the same issues even with the v130.0.2849.56 release.

**Comment by sandeepchads** [comment] 2024-10-29 11:24
Hi @Droxi-Raveh - you should update Edge and this issue should subside.

**Comment by ericlaw1979** [comment] 2024-10-29 13:18
> Hi, we're still experiencing the same issues even with the v130.0.2849.56 release.

Can you please provide specific details (e.g. extension info, what the code you're using is)? It seems good from here:

![Image](https://github.com/user-attachments/assets/1eb959f8-0fb9-433b-b207-8706ae4e7550)

**Comment by Droxi-Raveh** [comment] 2024-10-31 04:55
Appreciate that, seems like I may have jumped the gun on that one. Now working properly :)

**Closed** 2024-12-16 12:20 UTC
Labels: Bug, Edge Addons

**Comment by jcompagner** [comment] 2025-04-08 14:05
is this broken again in 135?  Because 134 the Keepassxc extension works fine, but "storage.managed.get(xxx)" doesn't return
