### ISSUE TITLE
[Bug - Edge Addons] Add-ons site fails to load intermittently

### ISSUE THREAD

**Issue by oliverdunk** [microsoft/MicrosoftEdge-Extensions#31] opened 2022-06-14 08:51 UTC
**Describe the bug**

I'm seeing intermittent errors loading the add-ons site:

<img width="1776" alt="image" src="https://user-images.githubusercontent.com/6097064/173535345-bfd36681-fad7-4d8b-b72a-1716e699d39f.png">

**To Reproduce**

Repeatedly load https://microsoftedge.microsoft.com/, and eventually you'll see an error. It took me a dozen or so attempts to reproduce this.

Sometimes this error is user visible, and other times you can see failed API requests in the network tab with similar responses from Falcon.

**Expected behavior**

No errors!

**Desktop (please complete the following information):**

Reproduced in both Edge and Chrome on macOS.

**Additional context**

Today is my first time noticing this. If it resolves itself, I'll let you know!

**Comment by m1kaj** [comment] 2022-06-16 09:07
I saw this error yesterday, roughly 24 hours ago. OS is Windows 10. My daily steps are: start Windows sandbox --> start Edge in sandbox --> (...) --> Extensions --> Manage extensions --> search and install one add-on. 

It took me about 10 attempts to load the page, search and install one add-on. Yesterday was the first and only time I have seen the problem. It works fine for me right now.

**Comment by nagachaitanyalokam** [comment] 2022-06-16 09:09
Thanks for adding details of your experience. Updated our engineering team with the info shared.

**Comment by nagachaitanyalokam** [comment] 2022-07-15 07:06
Our engineering team has confirmed that the issue is now fixed. Could you please check and let us know if you're still facing the issue or there's anything else we could help you with. Thanks!

**Closed by nagachaitanyalokam** 2022-07-15 07:06 UTC
Labels: Bug, Edge Addons, Reviewing
