### ISSUE TITLE
Edge Add-ons Publish API is now live!

### ISSUE THREAD

**Issue by JohnnyDa5** [microsoft/MicrosoftEdge-Extensions#146] opened 2024-04-12 01:32 UTC
![Uploading 20200210_221039.jpg…]()
## Discussed in https://github.com/microsoft/MicrosoftEdge-Extensions/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **nagachaitanyalokam** May  6, 2022</sup>
With this addition, you can integrate APIs directly into your build pipeline and deploy packages and publish updated versions without visiting the Partner Center.  

To learn more, you can check the below documentations: 

[Using the Microsoft Edge Add-ons API](https://aka.ms/Using_MSFTEdgeAddons_API) 
[Microsoft Edge Add-ons API Reference](https://aka.ms/MSFTEdgeAddons_API_Reference)

Read more about changes made to streamline the process of submitting a Microsoft Edge extension [here](https://techcommunity.microsoft.com/t5/articles/what-s-new-on-microsoft-partner-center-for-edge-add-on/m-p/3270268)</div>

**Comment by RanadhirMSFT** [comment] 2024-06-05 09:45
Hi @JohnnyDa5 , the image you have shared is broken. Could you re-send the image or give us more details about the trouble you are facing? This would help our team understand what exact problem you are dealing with and come up with a solution.

**Comment by sandeepchads** [comment] 2024-06-14 05:51
@JohnnyDa5 - thank you for celebrating the add-ons API release. Since this is not a bug, closing it for now. Happy to hear back from you.

**Closed by sandeepchads** 2024-06-14 05:52 UTC
Labels: Bug, Waiting for more info, Edge Addons
